apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: lookatme-k8s
  region: us-west-1

managedNodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    spot: true
    ssh:
      publicKeyName: M4